apiVersion: apps/v1
kind: Deployment

metadata:
  name: investment-order-service

spec:
  replicas: 3

  selector:
    matchLabels:
      app: investment-order-service

  template:
    metadata:
      labels:
        app: investment-order-service

    spec:
      containers:
      - name: app
        image: investment-order-service:v1

        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"